# code: language=ansible
---
- name: Setting OS variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars/os_family

- name: Set bht_config
  ansible.builtin.set_fact:
    bht_config: >-
      {{ bht_defaults | ansible.builtin.combine(
        (bht | default(bht_defaults))
      ) }}

- name: Print bht_config dictionary if debug flag is set
  ansible.builtin.debug:
    var: bht_config
  when: bht_config.debug

- name: Install core dependencies
  ansible.builtin.package:
    name: '{{ package }}'
    state: present
  when: (bht_config.state | string) == 'present'
  loop: '{{ bht_config.core_dependencies | list }}'
  loop_control:
    loop_var: package

- name: Install additional dependencies
  ansible.builtin.package:
    name: '{{ package }}'
    state: '{{ bht_config.state | string }}'
  loop: '{{ bht_config.additional_dependencies | list }}'
  loop_control:
    loop_var: package

- name: 'Ensure home directory exists'
  ansible.builtin.file:
    path: '{{ bht_config.home_directory | string }}'
    state: directory
    mode: '0755'
  when: (bht_config.state | string) == 'present'

- name: Install bht
  ansible.builtin.include_tasks: install.yml
  when: (bht_config.state | string) == 'present'

- name: Uninstall bht
  ansible.builtin.include_tasks: uninstall.yml
  when: (bht_config.state | string) == 'absent'
